<a href="https://colab.research.google.com/github/stefkong1982/netology.ru/blob/Master/Matematika_dlya_Data_Science/DZ_Kondratev_MDS_36_HW_2_upd.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Домашнее задание "Линейная алгебра. Матрицы".

## Уровень 0:


### Задание 1

 - Создайте матрицу 3 на 3, заполненную числами от 1 до 9
 - Прибавьте к ней матрицу с единицами на диагонале
 - Умножьте полученную матрицу на вектор (1, 2, 3)
 - Вычислить транспонированную матрицу $A^T$ от полученной в результате прибавления матрицы
 - Посчитайте обратную матрицу к полученной в результате прибавления матрице


In [3]:
import numpy as np

# Создание матрицы A
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [4]:
# Создание матрицы B (единичная матрица)
B = np.eye(3)
B

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [5]:
# Сложение матриц A и B
C = A + B
C

array([[ 2.,  2.,  3.],
       [ 4.,  6.,  6.],
       [ 7.,  8., 10.]])

In [8]:
# Создание вектора
D = np.array([1, 2, 3])
D

array([1, 2, 3])

In [9]:
# Умножение матрицы C на вектор D
result = np.dot(C, D)
result

array([15., 34., 53.])

In [11]:
# Транспонирование матрицы C
AT = np.transpose(C)
AT

array([[ 2.,  4.,  7.],
       [ 2.,  6.,  8.],
       [ 3.,  6., 10.]])

In [13]:
# Вычисление обратной матрицы к C
try:
    inv_C = np.linalg.inv(C)
except np.linalg.LinAlgError:
    inv_C = None
inv_C

array([[-6.00000000e+00, -2.00000000e+00,  3.00000000e+00],
       [-1.00000000e+00,  5.00000000e-01, -2.33146835e-16],
       [ 5.00000000e+00,  1.00000000e+00, -2.00000000e+00]])

In [14]:
print("Сумма матриц A и B:")
print(C)

print("\nУмножение матрицы C на вектор D:")
print(result)

print("\nТранспонированная матрица C:")
print(AT)

print("\nОбратная матрица к матрице C:")
print(inv_C)

Сумма матриц A и B:
[[ 2.  2.  3.]
 [ 4.  6.  6.]
 [ 7.  8. 10.]]

Умножение матрицы C на вектор D:
[15. 34. 53.]

Транспонированная матрица C:
[[ 2.  4.  7.]
 [ 2.  6.  8.]
 [ 3.  6. 10.]]

Обратная матрица к матрице C:
[[-6.00000000e+00 -2.00000000e+00  3.00000000e+00]
 [-1.00000000e+00  5.00000000e-01 -2.33146835e-16]
 [ 5.00000000e+00  1.00000000e+00 -2.00000000e+00]]


## Уровень 1:

### Задание 2

Найдите собственные значения и собственные вектора матрицы:
```
m = np.array([[2, 2],
              [1, 3]])
print(m)
```



In [ ]:
### YOUR CODE HERE

### Задание 3


Придумайте матрицу, у которой определитель = 1, и все элементы не равны 0.

P.S. Матрица должна быть ненулевой и размерностью не менее 2!

In [ ]:
### YOUR CODE HERE