<a href="https://colab.research.google.com/github/stefkong1982/netology.ru/blob/Master/Matematika_dlya_Data_Science/Linejnaya_algebra_Matricy/DZ_Kondratev_MDS_36_HW_2_upd.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Домашнее задание "Линейная алгебра. Матрицы".

## Уровень 0:


### Задание 1

 - Создайте матрицу 3 на 3, заполненную числами от 1 до 9
 - Прибавьте к ней матрицу с единицами на диагонале
 - Умножьте полученную матрицу на вектор (1, 2, 3)
 - Вычислить транспонированную матрицу $A^T$ от полученной в результате прибавления матрицы
 - Посчитайте обратную матрицу к полученной в результате прибавления матрице


In [ ]:
import numpy as np

# Создание матрицы A
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

# Создание матрицы B (единичная матрица)
B = np.eye(3)

# Сложение матриц A и B
C = np.add(A, B)

# Создание вектора
D = np.array([1, 2, 3])

# Умножение матрицы C на вектор D
result = np.dot(C, D)

# Транспонирование матрицы C
AT = np.transpose(C)

# Вычисление обратной матрицы к C
try:
    inv_C = np.linalg.inv(C)
except np.linalg.LinAlgError:
    inv_C = None

print("Сумма матриц A и B:")
print(C)

print("\nУмножение матрицы C на вектор D:")
print(result)

print("\nТранспонированная матрица C:")
print(AT)

if inv_C is not None:
    print("\nОбратная матрица к матрице C:")
    print(inv_C)
else:
    print("\nОбратная матрица к матрице C не существует.")


Сумма матриц A и B:
[[ 2.  2.  3.]
 [ 4.  6.  6.]
 [ 7.  8. 10.]]

Умножение матрицы C на вектор D:
[15. 34. 53.]

Транспонированная матрица C:
[[ 2.  4.  7.]
 [ 2.  6.  8.]
 [ 3.  6. 10.]]

Обратная матрица к матрице C:
[[-6.00000000e+00 -2.00000000e+00  3.00000000e+00]
 [-1.00000000e+00  5.00000000e-01 -2.33146835e-16]
 [ 5.00000000e+00  1.00000000e+00 -2.00000000e+00]]


## Уровень 1:

### Задание 2

Найдите собственные значения и собственные вектора матрицы:
```
m = np.array([[2, 2],
              [1, 3]])
print(m)
```



In [ ]:
import numpy as np

m = np.array([[2, 2],
              [1, 3]])

# Вычисление собственных значений
eigenvalues = np.linalg.eigvals(m)

# Вычисление собственных векторов
eigenvectors = np.linalg.eig(m)[1]

# Вывод собственных значений и векторов
print("Собственные значения:")
print(eigenvalues)

print("\nСобственные векторы:")
print(eigenvectors)


Собственные значения:
[1. 4.]

Собственные векторы:
[[-0.89442719 -0.70710678]
 [ 0.4472136  -0.70710678]]


### Задание 3


Придумайте матрицу, у которой определитель = 1, и все элементы не равны 0.

P.S. Матрица должна быть ненулевой и размерностью не менее 2!

In [ ]:
import numpy as np
import random

while True:
    m = np.zeros((2, 2))

    # Генерируем случайные ненулевые элементы для каждой строки матрицы
    for i in range(2):
        non_zero_elements = random.sample(range(1, 10), 2)
        m[i] = non_zero_elements

    # Проверяем условие, что определитель матрицы равен 1
    if np.linalg.det(m) == 1:
        break

print("Сгенерированная матрица:")
print(m)

Сгенерированная матрица:
[[4. 5.]
 [3. 4.]]
